root: true
env:
  browser: true
  es2021: true
  node: true
  jest/globals: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/vue3-recommended'
  - 'plugin:prettier/recommended'
  - 'prettier'
plugins:
  - 'vue'
  - 'eslint-plugin-prettier'
  - 'jest'
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: 'module'
rules:
  prettier/prettier: 'error'
