root: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/vue3-recommended'
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: 12
  parser: '@typescript-eslint/parser'
  sourceType: 'module'