extends:
  - stylelint-config-standard
  - stylelint-config-recess-order
  - stylelint-config-recommended-vue
  - stylelint-config-recommended-scss
  - stylelint-prettier/recommended
customSyntax: postcss-html
